# Generated by Django 5.2.4 on 2025-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('access', models.CharField(blank=True, max_length=100, null=True)),
                ('useragent', models.CharField(blank=True, max_length=255, null=True)),
                ('antivirus', models.CharField(blank=True, max_length=100, null=True)),
                ('computer', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8, null=True)),
            ],
        ),
    ]
